// netlify/functions/chatboot.js
// Files Coaching — Chatbot IA only (FR by default, EN on request).
// No canned replies: everything is generated by the LLM,
// with strict safeguards: NO full workouts, NO nutrition/recipes.
// If user asks those → redirect to the questionnaire URL below.

// ★ URL normalisée (sans espaces, avec https) + possible override via env
const QUESTIONNAIRE_URL = (process.env.QUESTIONNAIRE_URL || "https://appli.files-coaching.com").trim();

const low  = (s) => (s || "").toLowerCase();
const any  = (t, arr) => arr.some(k => t.includes(k));
const isEmpty = (v) => !v || !String(v).trim();

// --- simple language detection: default FR, switch to EN if clear English cues
function detectLang(msg) {
  const t = low(msg);
  if (any(t, [
    "english", "in english", "answer in english", "hey", "hello", "hi",
    "workout", "training", "price", "cost", "meal", "diet", "food", "help", "please"
  ])) return "en";
  return "fr";
}

// --- intents that must be redirected (no generation)
const BLOCK_KEYS = {
  fr: {
    workout: ["séance", "seance", "programme", "exercice", "exos", "plan d'entraînement", "plan d entrainement", "routine", "planning", "workout", "programme complet", "séance complète", "seance complete"],
    nutrition: ["nutrition", "recette", "recettes", "repas", "plan nutrition", "plan alimentaire", "alimentation", "macro", "calorie", "protéine", "proteine", "glucide", "lipide", "menu"]
  },
  en: {
    workout: ["workout plan", "full workout", "session plan", "program", "routine", "training plan", "complete session", "complete program", "exercises plan"],
    nutrition: ["nutrition plan", "meal plan", "diet plan", "exact macros", "recipes", "recipe", "calories", "protein", "carbs", "fats", "menu"]
  }
};

// ★ détection d’intention par mots-clés (FR/EN)
function detectBlockedIntent(msg, lang) {
  const t = low(msg);
  const dict = BLOCK_KEYS[lang] || BLOCK_KEYS.fr;
  for (const [topic, keys] of Object.entries(dict)) {
    if (any(t, keys)) return topic; // "workout" | "nutrition"
  }
  return null;
}

// --- redirection text (désormais URL brute, pas d’ancre)
function redirectReply(/* lang, topic */) {
  return QUESTIONNAIRE_URL; // ★ pas de <a>, juste l’URL (ton UI l’auto-linkera)
}

// --- OpenAI call (Chat Completions)
async function callLLM({ userMessage, lang }) {
  const apiKey = process.env.OPENAI_API_KEY;
  const model  = process.env.OPENAI_MODEL || "gpt-4o-mini";
  const base   = process.env.OPENAI_BASE_URL || "https://api.openai.com/v1";
  if (!apiKey) throw new Error("Missing OPENAI_API_KEY");

  const system = (lang === "en")
    ? [
        "You are Files, a helpful fitness assistant for files-coaching.com.",
        "NEVER provide full workouts, routines, or complete training programs.",
        "NEVER provide exact nutrition plans, recipes, or exact macros/calories.",
        `If the user asks for those, tell them to use the questionnaire: ${QUESTIONNAIRE_URL}.`,
        "Keep answers concise (1–3 sentences), friendly, and actionable.",
        "You may help with site navigation and general guidance."
      ].join("\n")
    : [
        "Tu es Files, un assistant de coaching sportif pour files-coaching.com.",
        "NE DONNE JAMAIS de séances complètes, routines ou programmes d'entraînement complets.",
        "NE DONNE JAMAIS de plans nutrition précis, de recettes exactes ni de macros/calories exactes.",
        `Si l'utilisateur le demande, redirige-le vers le questionnaire : ${QUESTIONNAIRE_URL}.`,
        "Réponds de façon concise (1–3 phrases), amicale et utile.",
        "Tu peux aider à la navigation du site et donner des conseils généraux."
      ].join("\n");

  const res = await fetch(`${base}/chat/completions`, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: system },
        { role: "user", content: userMessage }
      ],
      temperature: 0.6
    })
  });

  if (!res.ok) {
    const t = await res.text().catch(() => "");
    throw new Error(`LLM ${res.status}: ${t.slice(0,200)}`);
  }
  const json = await res.json();
  const out = json.choices?.[0]?.message?.content?.trim();
  return out || (lang === "en" ? "I’m not sure I understood." : "Je ne suis pas sûr d’avoir compris.");
}

// --- final safety: if the model tries to output restricted content, replace by redirect
function safetyPostFilter(text, lang) {
  const bad = /(full (workout|program)|séance complète|programme complet|meal plan|nutrition plan|exact (macros?|calories)|recettes?\b)/i;
  if (bad.test(text)) {
    return redirectReply(lang, /(meal plan|nutrition|recette|recipes?)/i.test(text) ? "nutrition" : "workout");
  }
  return text;
}

exports.handler = async (event) => {
  // --- CORS headers (ok pour tests locaux; restreins à ton domaine en prod)
  const CORS = {
    "Access-Control-Allow-Origin": "*", // ex: "https://files-coaching.netlify.app"
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Methods": "POST, GET, OPTIONS"
  };
  const headers = { "Content-Type": "application/json", ...CORS };

  try {
    // Preflight & health
    if (event.httpMethod === "GET") {
      return { statusCode: 200, headers, body: JSON.stringify({ ok: true, reply: "AI ready ✅" }) };
    }
    if (event.httpMethod === "OPTIONS") {
      return { statusCode: 200, headers, body: "" };
    }

    // Parse input
    const body = event.body ? JSON.parse(event.body) : {};
    const message = String(body.message || "").trim();
    const lang = body.lang || detectLang(message); // priorité à la langue envoyée par le front
    if (isEmpty(message)) {
      return { statusCode: 200, headers, body: JSON.stringify({ reply: "Dis-moi quelque chose 🙂 / Say something 🙂", lang }) };
    }

    // ★ 1) Redirect immédiat si mots-clés "bloquants"
    const topic = detectBlockedIntent(message, lang);
    if (topic) {
      // reply = URL brute et champ "redirectTo" pour que le front puisse rediriger sans clic
      const reply = redirectReply(lang, topic);
      return {
        statusCode: 200,
        headers,
        body: JSON.stringify({
          reply,            // ex: "https://questionnaire.files-coaching.com"
          lang,
          redirectTo: QUESTIONNAIRE_URL, // ★ ton front peut faire: if (data.redirectTo) window.location.assign(data.redirectTo)
          topic
        })
      };
    }

    // 2) Sinon, appel LLM
    let ai = await callLLM({ userMessage: message, lang });

    // Logging (n8n) hors-flux
    try {
      const payload = {
        created_at: new Date().toISOString(),
        lang,
        user: message,
        ai
      };
      fetch(process.env.N8N_WEBHOOK_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      }).catch(() => {});
    } catch (e) {
      console.error("n8n log error:", e);
    }

    // 3) Safety post-filter
    ai = safetyPostFilter(ai, lang);

    return { statusCode: 200, headers, body: JSON.stringify({ reply: ai, lang }) };
  } catch (e) {
    console.error("chatboot error:", e);
    const lang = "fr";
    // ★ Fallback en URL brute
    const reply = `Besoin d’un plan complet ? ${QUESTIONNAIRE_URL}`;
    // Renvoie 200 pour éviter d'afficher une erreur côté UI
    return { statusCode: 200, headers, body: JSON.stringify({ reply, lang }) };
  }
};
